-- +goose Up
create table drivers (
  id bigint generated by default as identity primary key,
  username text not null unique check (username ~ '^[a-z0-9][a-z0-9_-]{0,31}$'),
  display_name text not null check (char_length(display_name) between 1 and 60),
  created_at timestamptz not null default now()
);
insert into drivers (username, display_name) values ('caleb', 'Caleb');
alter table app_profile add column driver_id bigint references drivers(id) on delete cascade;
update app_profile set driver_id = (select id from drivers where username = 'caleb');
alter table app_profile drop constraint app_profile_singleton, drop constraint app_profile_pkey, drop column id;
alter table app_profile alter column driver_id set not null, add primary key (driver_id);
alter table requirement_items add column driver_id bigint references drivers(id) on delete cascade;
update requirement_items set driver_id = (select id from drivers where username = 'caleb');
alter table requirement_items drop constraint requirement_items_pkey, drop constraint requirement_items_sort_order_key;
alter table requirement_items alter column driver_id set not null, add primary key (driver_id, key), add unique (driver_id, sort_order);
alter table requirement_items rename column mastered_date to rated_on;
alter table requirement_items drop constraint requirement_items_status_valid;
update requirement_items set status = case status when 'mastered' then 'good' else 'fair' end;
alter table requirement_items alter column status set default 'not_rated', add constraint requirement_items_status_valid check (status in ('not_rated','bad','fair','good'));

-- +goose Down
-- Downgrading intentionally discards every driver's data except Caleb's.
delete from drivers where username <> 'caleb';
alter table requirement_items drop constraint requirement_items_status_valid;
update requirement_items set status = case status when 'good' then 'mastered' else 'needs_practice' end;
alter table requirement_items alter column status set default 'needs_practice', add constraint requirement_items_status_valid check (status in ('needs_practice','mastered'));
alter table requirement_items rename column rated_on to mastered_date;
alter table requirement_items drop constraint requirement_items_pkey, drop constraint requirement_items_driver_id_sort_order_key, drop column driver_id;
alter table requirement_items add primary key (key), add unique (sort_order);
alter table app_profile drop constraint app_profile_pkey, drop column driver_id;
alter table app_profile add column id integer not null default 1 primary key, add constraint app_profile_singleton check (id = 1);
drop table drivers;
